### ISSUE TITLE
线性回归那篇文章里的行内公式渲染似乎有问题诶

### ISSUE THREAD

**Issue by namasikanam** [jcq15/blog#1]
[《线性回归快速开始》](https://blog.shadiao.online/post/linearregression/)里的公式渲染似乎挂了，参照[这个 issue 里的回答](https://github.com/KaTeX/KaTeX/issues/1481)，似乎 KaTeX 需要用 `\(...\)` 来提供行内公式环境，而不是 `$...$`？

**Comment by jcq15** [comment]
感谢指出！已经修复了。使用了[这个解决方案](https://note.qidong.name/2018/03/hugo-mathjax/#%e6%9c%ac%e7%ab%99%e6%96%b0%e6%96%b9%e6%a1%882020%e5%b9%b4%e6%9b%b4%e6%96%b0)。
